cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/del/$', views.delevent, name='event_del'),
    url(r'^login/$', views.login, name='login'),
    url(r'^emails/$', views.emails, name='emails'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from cal import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    
    
    path('',views.login)
    
]

cal/models.py
from django.db import models
from django.urls import reverse

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
 

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
       
        return f'<a href="{url}"> {self.title} </a>'
class Email(models.Model):
    name = models.CharField(max_length=200)
    event_id = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    email1 = models.TextField()
    email2 = models.TextField()
    email3 = models.TextField()
 

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
       
        return f'<a href="{url}"> {self.title} </a>'


class DelEvent(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:event_del', args=(self.id,))
       
        return f'<a href="{url}"> {self.title} </a>'
    

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event,DelEvent,Email
class EventForm(ModelForm):
 
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'
  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)
class EmailForm(ModelForm):
 
  class Meta:
    model = Email
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'
  def __init__(self, *args, **kwargs):
    super(EmailForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class DelEventForm(ModelForm):
 
  class Meta:
    model = DelEvent
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'
  def __init__(self, *args, **kwargs):
    super(DelEventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

cal/views.py
import datetime
from datetime import timedelta, date
import time
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
import ssl
from .models import *
from .utils import Calendar
from .forms import EventForm,DelEventForm,EmailForm
import csv
from json import dumps
import smtplib

def index(request):
    return HttpResponse('hello')



class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.date.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def login(request,event_id = None):
    file = "login_det"
    csv_fp = open(f'{file}.csv', 'r')
    reader = csv.DictReader(csv_fp)
    headers = [col for col in reader.fieldnames]
    out = [row for row in reader]
    print(out)
    headers = dumps(headers)
    row = dumps(out)
    return render(request, 'cal/login.html',{'row': row,headers:'headers'})

    return render(request,'cal/login.html')

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    forming = str(form)
    file1 = open("eventlogs.txt", "a")
    #file2 = open("login_det.csv","r")
    #for i in file2:
    #    print(i)

    file1.write("Title  ")
    file1.write("Start Date       ")
    file1.write("End Date         ")
    file1.write("\n")
    for i in forming.split(" "):
        if "value" in i:
            file1.write(i[7:])
            file1.write(" ")
    file1.write("\n")
    return render(request, 'cal/event.html', {'form': form})
def emails(request):

    '''
    five_minutes = datetime.timedelta(minutes=5)
    final_datetime = initial_datetime - five_minutes
    print("reminder time = ",final_datetime)
    current_time = datetime.datetime.now()
    print("current time = ",current_time)
    print(final_datetime.timestamp() - current_time.timestamp())
    #time.sleep(final_datetime.timestamp() - current_time.timestamp())


    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = "bhargu2000@gmail.com" 
    password = "qwerty@123"
    message = """
    Subject: Calendar App
            
    Hello
    Your event is starting in 5 minutes."""

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        #x = time.sleep(send_time.timestamp() - time.time())
        for i in range(len(email_list)):
            server.sendmail(sender_email, email_list[i], message)
    '''
    return render(request, 'cal/emails.html')

    
    #email_list = ["thrupthijyo22@gmail.com","nishasuresh2001@gmail.com", "bhargu2000@gmail.com"]
    #initial_datetime = datetime.datetime(2021, 4, 7, 10, 25, 0)
    #email_notify(email_list, initial_datetime)
    

def delevent(request, event_id=None):
    instance = DelEvent()
    if event_id:
        instance = get_object_or_404(DelEvent, pk=event_id)
    else:
        instance = DelEvent()

    form = DelEventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    
    return render(request, 'cal/event.html', {'form': form})


    

cal/templates/cal/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}

<script>
	function myFunction() {
	  var x = document.getElementById("myDIV");
	  if (x.style.display === "none") {
		x.style.display = "block";
	  } else {
		x.style.display = "none";
	  }
	}
	</script>
	<div id="myDIV">
	 
		<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
		<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
		<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
		<a class="btn btn-info right" href="{% url 'cal:login' %}"> login </a>
		<a class="btn btn-info right" href="{% url 'cal:emails' %}"> send invite </a>
		
	</div>
	<tr><td colspan="2"><button type="submit" class="btn btn-info left"  onclick="myFunction()"> delete </button></td></tr>
{{ calendar }}
{% endblock %}

cal/templates/cal/del.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}




<form action = "" method="post">
  {% csrf_token %}
     {{form}}
   
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> del </button></td></tr>

  
</form>
{% endblock %}

cal/templates/cal/emails.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
/* Style all input fields */
input {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
}

/* Style the submit button */
input[type=submit] {
  background-color: #4CAF50;
  color: white;
}

/* Style the container for inputs */
.container {
  background-color: #f1f1f1;
  padding: 20px;
}

/* The message box is shown when the user clicks on the password field */
#message {
  display:none;
  background: #f1f1f1;
  color: #000;
  position: relative;
  padding: 20px;
  margin-top: 10px;
}

#message p {
  padding: 10px 35px;
  font-size: 18px;
}

/* Add a green text color and a checkmark when the requirements are right */
.valid {
  color: green;
}

.valid:before {
  position: relative;
  left: -35px;
  content: "✔";
}

/* Add a red text color and an "x" when the requirements are wrong */
.invalid {
  color: red;
}

.invalid:before {
  position: relative;
  left: -35px;
  content: "✖";
}
.clearfix {
  margin: 15px;
}
</style>
<script src=
"https://smtpjs.com/v3/smtp.js">
</script>
<script>
        function sendemail()
        {
            var email = document.getElementById("email1").value;
            var subject = ('My permanent subject line');
            var body = ('My permanent body contents');
            document.write('<a href="mailto:' + email + '?subject=' +subject+ '&body=' +body+ '">' + 'Click here to send email as well' + '<'+'/a>');
        }




 
    
  </script>
</head>
<body>

<h1 align = "center">Event share</h1>
<p>Try to submit the form.</p>
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>
<div class="container">
  <form method = "post">
    {% csrf_token %}

    
    <label for="email">Enter your email1:</label><br>
    <input type="email" id="email1" name="email">

    
    <input type="submit" value="send invite" onclick="sendemail()">
  </form>
</div>

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}


<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>

  </table>
</form>
<h1>Enter the details of the new event in this form and select del only if you want the previous event to be deleted.  </h1>
<form action = "" method="post">
  {% csrf_token %}
  <table class="form form-table">
     {{form}}
   
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> del </button></td></tr>
</table>
  
</form>
{% endblock %}

cal/templates/cal/front_page.html
<html>  
<head>  
    <title>Cal App</title>  
    <!-- insert style.css file inside index.html -->
    <link rel = "stylesheet" type = "text/css" href = "style.css">  
</head>  
<body>  
    <style>
	body {
		  background-image: url('2020_cover_calendar.jfif');
		  background-repeat: no-repeat;
		  background-attachment: fixed;
		  background-size: 100% 100%;
	     }
    </style>
    <div id = "frm">
        <h1>Cal App</h1> 
        <form name="f1" action = "authentication.php" onsubmit = "return validation()" method = "POST">  
            <p>  
                <label> Email id: </label>  
                <input type = "email" id ="email" name  = "email" />  
            </p>  
            <p>  
                <label> Password: </label>  
                <input type = "password" id ="pass" name  = "pass" />  
            </p>  
            <p>     
                <input type =  "submit" id = "btn" value = "Login" />  
            </p>  
        </form>  
    </div>  
    <!-- validation for empty field  --> 
    <script>  
            function validation()  
            {  
                var id=document.f1.email.value;  
                var ps=document.f1.pass.value;  
                if(id.length=="" && ps.length=="") {  
                    alert("User Name and Password fields are empty");  
                    return false;  
                }  
                else  
                {  
                    if(id.length=="") {  
                        alert("Email field is empty");  
                        return false;  
                    }   
                    if (ps.length=="") {  
                    alert("Password field is empty");  
                    return false;  
                    }  
                }                             
            }  
        </script>  
</body>     
</html>  

cal/templates/cal/login.html
<html>
  <head>
    
    {% load static %}
    <title>Cal App</title>  
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  </head>
  <style>
    #image {
        width : 100%;
        height : 800px;
        background-image: {% load static %}url({% static "2020_cover_calendar.jfif" %})
      
    }
    body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}
#form{
  position:fixed;
   top:40%;
   left:40%;
   width:1500px;
}

input[type=text] {
  width: 20%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}
input[type=password] {
  width: 20%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=button] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=button]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
    </style>
 
    <h1 align = "center">Login Page</h1>
  <div id = image>
    <div class="container">
  <form id = "form">
    
    <input type="text" placeholder="Username" id="text1" required/><br />
    
    <input type="password" placeholder="Password" id="text2" required/><br />
    <input type="button" value="Login"  onclick="javascript:validate()" />
  </form>
</div>


</div>


  
 <script type="text/javascript">
 

  function validate()
  {
    var counts = JSON.parse("{{ row|escapejs }}");
    var i;
    
      for(i = 0; i < counts.length; i++) 
      {
        if(   document.getElementById("text1").value == counts[i]['username']
          && document.getElementById("text2").value == counts[i]['password'] )
          {
              alert( "validation succeeded" );
              var a = document.createElement('a');
              var link = document.createTextNode("This is link");
              a.appendChild(link);
              a.title = "Calendar";
              a.href = "{% url 'cal:calendar' %}";
              document.body.appendChild(a);
            
              break;

          }
      }
      if(i==counts.length)
      {
        alert("validation failed")
      }
 
  }

</script>



</html>

cal/templates/cal/save.html
<label for="usrname">Event name</label><br>
<input type="text" id="Eventname" name="Eventname" required>

<label for="usrname">Event id</label><br>
<input type="text" id="Eventid" name="Eventid" required>

<label for="starttime">start (date and time):</label><br>
<input type="datetime-local" id="starttime" name="starttime">

<label for="email">Enter your email1:</label><br>
<input type="email" id="email" name="email">

<label for="email">Enter your email2:</label><br>
<input type="email" id="email" name="email">

<label for="email">Enter your email3:</label><br>
<input type="email" id="email" name="email">